### ISSUE TITLE
Can't set grade, JavaScript error in Firefox 28.0

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/obsolete-edx-sga#14]
I've tested this in Firefox 28.0 and Chrome (some version). I'm only seeing the issue in Firefox. 

When I'm in the "Enter Grade" dialog and I click the submit button, my changes to the grade and the comment aren't saved.

In the JavaScript console, I see an error
associated with the request https://sandbox0r.mitx.mit.edu/courses/MITx/edx4edx/edx4edx/courseware/Assessment_Problems_chapter/Sample_Problems_sequential/?module_id=710&grade=36&comment=thirty-six

ReferenceError: event is not defined

FWIW, removing a grade appears to work.

**Comment by chrisrossi** [comment]
The fix for #16 also fixed this one.
