### ISSUE TITLE
Grade above maximum is still stored

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/obsolete-edx-sga#16]
When I enter a grade above the max allowed for the problem, I get an error message, but the grade is submitted & stored anyway.

I am testing on https://sandbox0r.mitx.mit.edu/courses/MITx/edx4edx/edx4edx/courseware/Assessment_Problems_chapter/b67a3c71a81b488f94ff5eba6884f0ca/

**Comment by chrisrossi** [comment]
Fixed.
