### ISSUE TITLE
Need validation for edit view

### ISSUE THREAD

**Issue by chrisrossi** [jazkarta/obsolete-edx-sga#3]
The edit view currently has no validation.  It is possible to, for example, enter a non-numeric value for "weight" and render the xblock unusable.

**Comment by pdpinch** [comment]
Is this our XBlock's responsibility, or is this a shortcoming in Studio?

**Comment by chrisrossi** [comment]
Eventually, I'm told, there will be a facility for generating edit UI for Xblocks.  Until then it's our responsibility.  If you can live with current functionality, it might make sense to wait to avoid doing work that will be thrown away when an eventual switch to the official way of doing things is made.
