### ISSUE TITLE
Uploading a too-large file should fail with an error message returned to the user. 

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/obsolete-edx-sga#6]
I tried uploading a 5.2MB file, which should be too large for the 5MB limiit on nginx. 

The upload indicator advanced to 100%, and then nothing happened. I am left without a browse button to upload another file. 

The behavior should be to return an error message to the user and then allow him to upload again. 

For the error message, how about "Sorry, that file is too large. Please upload a smaller file"

If it's possible to either report the size of the file that was too large or, even better, the limit (imposed by configuration) that would be nice to have in the error.

**Comment by chrisrossi** [comment]
Fixed.

**Comment by carsongee** [comment]
Testing this with an nginx server in front of it is still resulting in a the upload progress going to 100%, and then nothing happens if the file is too large.  As an additional side effect, the upload button is gone during this, so you can't try again without refreshing the page.

**Comment by chrisrossi** [comment]
Fixed.
