### ISSUE TITLE
SGA Component should observe sub-section due date

### ISSUE THREAD

**Issue by pdpinch** [jazkarta/obsolete-edx-sga#7]
When an SGA appears in a subsection with a due date, it should no longer allow uploads after the due date. 

I believe there was a message in the prototype that replaces the "Upload a File... " ui element. If not, let me know and we'll compose something.

**Comment by pdpinch** [comment]
My test case is at https://sandbox0r.mitx.mit.edu/courses/MITx/edx4edx/edx4edx/courseware/Assessment_Problems_chapter/b67a3c71a81b488f94ff5eba6884f0ca/#

**Comment by chrisrossi** [comment]
This is fixed.  Please confirm.

**Comment by pdpinch** [comment]
This works now in Student View. 

In Staff view, the problem also observes the due date, which is contrary to current practice. I'll open that as another, low-priority issue.
